package com.example.spotifywrapper.fragments.app;

import android.content.Intent;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModelProvider;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import com.example.spotifywrapper.R;
import com.example.spotifywrapper.StoryActivity;
import com.example.spotifywrapper.model.Wrapped;
import com.example.spotifywrapper.utils.CustomAdapter;
import com.example.spotifywrapper.utils.SharedViewModel;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import org.checkerframework.checker.units.qual.A;
import org.checkerframework.checker.units.qual.C;

import java.util.ArrayList;

/**
 * This fragment will show the past wrappeds generated by the user
 */
public class HistoryFragment extends Fragment {

    private static final String TAG = "HistoryFragment";
    private FirebaseAuth mAuth;
    private FirebaseFirestore db;
    private Gson gson;
    private SharedViewModel viewModel;
    private ArrayList<Wrapped> list;
    private RecyclerView recyclerView;
    private CustomAdapter adapter;

    public HistoryFragment() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.

     * @return A new instance of fragment NavigationFragment.
     */
    // TODO: Rename and change types and number of parameters
    public static HistoryFragment newInstance() {
        HistoryFragment fragment = new HistoryFragment();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mAuth = FirebaseAuth.getInstance();
        db = FirebaseFirestore.getInstance();
        gson = new Gson();
        list = new ArrayList<>();

        viewModel = new ViewModelProvider(requireActivity()).get(SharedViewModel.class);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View rootView =  inflater.inflate(R.layout.fragment_history, container, false);
        recyclerView = rootView.findViewById(R.id.rv_saved_wrapped);

        generateView();

        return rootView;
    }

    @Override
    public void onResume() {
        super.onResume();

    }

    private void generateView() {
        viewModel.getSaved_wrapped().observe(getViewLifecycleOwner(), saved_wrapped -> {
            list = saved_wrapped;
            adapter = new CustomAdapter(list);
            recyclerView.setLayoutManager(new LinearLayoutManager(requireActivity()));
            recyclerView.setAdapter(adapter);

            adapter.setOnClickListener(new CustomAdapter.OnClickListener() {
                @Override
                public void onClick(int position, Wrapped wrapped) {
                    String my_wrapped = gson.toJson(list.get(position));
                    Intent intent = new Intent(requireActivity(), StoryActivity.class);
                    intent.putExtra("wrapped_info", my_wrapped);
                    intent.putExtra("toBeSaved", false);
                    startActivity(intent);
                }
            });


        });
    }


}